name: flutter_facebook_auth
description: The easiest way to add facebook login to your flutter app, get user information, profile picture and more. Web support included.
version: 3.5.7
homepage: https://github.com/darwin-morocho/flutter-facebook-auth

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth_platform_interface:
    git:
      url: "git@github.com:lvdiep/flutter_plugin_facebook_auth.git"
      path: facebook_auth_platform_interface
      ref: 90c5e30
  flutter_facebook_auth_web:
    git:
      url: "git@github.com:lvdiep/flutter_plugin_facebook_auth.git"
      path: facebook_auth_web
      ref: 0cd3462


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: app.meedu.flutter_facebook_auth
        pluginClass: FlutterFacebookAuthPlugin
      ios:
        pluginClass: FlutterFacebookAuthPlugin
      web:
        default_package: flutter_facebook_auth_web
