name: facebook_auth_desktop
description: macOS support for flutter_facebook_auth
version: 0.0.7
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_secure_storage:
    git:
      url: "git@github.com:lvdiep/flutter_plugin_secure_storage.git"
      path: flutter_secure_storage
      ref: faef157
  # flutter_facebook_auth_platform_interface: ^4.1.1
  flutter_facebook_auth_platform_interface:
    git:
      url: "https://github.com/lvdiep/flutter_plugin_facebook_auth.git"
      path: facebook_auth_platform_interface


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    implements: flutter_facebook_auth
    platforms:
      macos:
        pluginClass: FacebookAuthDesktopPlugin
        dartPluginClass: FacebookAuthDesktopPlugin